/**
 * GET /api/pick-reasoning?date=YYYY-MM-DD&game_pk=N
 *
 * T4.12 -- surface T4.6's per-pick "Why this pick?" JSON in the dashboard
 * row expansion.  Returns the matching pick entry from
 *   data/diagnostics/picks/<date>.json
 * so the UI can render top LR feature contributions, raw vs priors-pooled
 * Statcast comparison, calibrator band info, and the warnings list.
 *
 * Query params:
 *   date     ISO date (YYYY-MM-DD), required
 *   game_pk  MLB game_pk (numeric or string), required
 *
 * Response shape (success):
 *   {
 *     "matchup":  "ARI@CHC",
 *     "game_pk":  "824687",
 *     "pick_side": "YRFI" | "NRFI" | "PASS",
 *     "pick_strength": "STRONG" | "PASS",
 *     "calibrated_p_nrfi": 0.376,
 *     "raw_p_nrfi": 0.331,
 *     "calibrator_band": { is_flat, flat_size, flat_rate },
 *     "top_drivers_t1": [{ name, value, z, weight, contribution, outlier }],
 *     "top_drivers_b1": [...],
 *     "priors_vs_raw":  { home_xera_raw, home_xera_pooled, away_xera_raw, away_xera_pooled },
 *     "pitcher_q":      { home_pitcher_q, away_pitcher_q },
 *     "warnings":       ["raw cache xera=14.71 outside [2.0, 7.0] ...", ...]
 *   }
 *
 * Response shape (no data yet for that game):
 *   { "available": false, "reason": "..." }
 */

import { NextRequest, NextResponse } from "next/server";
import fs from "node:fs";
import path from "node:path";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

function dataDir(): string {
  const local  = path.resolve(process.cwd(), "data");
  const parent = path.resolve(process.cwd(), "..", "data");
  try {
    if (fs.existsSync(path.join(parent, "diagnostics", "picks"))) return parent;
    if (fs.existsSync(path.join(local,  "diagnostics", "picks"))) return local;
    if (fs.existsSync(path.join(parent, "boards"))) return parent;
    if (fs.existsSync(path.join(local,  "boards"))) return local;
  } catch {
    /* ignore */
  }
  return local;
}

interface PickEntry {
  matchup:           string;
  game_pk:           string;
  pick_side:         string;
  pick_strength:     string;
  graded_result:     string;
  raw_p_nrfi:        number;
  calibrated_p_nrfi: number;
  calibrator_band:   Record<string, unknown>;
  top_drivers_t1:    Array<Record<string, unknown>>;
  top_drivers_b1:    Array<Record<string, unknown>>;
  priors_vs_raw:     Record<string, number | null>;
  pitcher_q:         Record<string, string | null>;
  warnings:          string[];
}

interface PicksFile {
  date:    string;
  picks:   PickEntry[];
  [k: string]: unknown;
}

export async function GET(req: NextRequest) {
  const { searchParams } = new URL(req.url);
  const date    = searchParams.get("date");
  const game_pk = searchParams.get("game_pk");

  if (!date || !game_pk) {
    return NextResponse.json(
      { available: false, reason: "Missing date or game_pk query param" },
      { status: 400, headers: { "cache-control": "no-store" } },
    );
  }
  if (!/^\d{4}-\d{2}-\d{2}$/.test(date)) {
    return NextResponse.json(
      { available: false, reason: "Invalid date format (need YYYY-MM-DD)" },
      { status: 400, headers: { "cache-control": "no-store" } },
    );
  }

  const filePath = path.join(dataDir(), "diagnostics", "picks", `${date}.json`);
  if (!fs.existsSync(filePath)) {
    return NextResponse.json(
      {
        available: false,
        reason: `No reasoning data for ${date} yet.  Generated by tools/pick_reasoning_log.py during the predict + grade crons; first available after the next predict cycle.`,
      },
      { headers: { "cache-control": "no-store" } },
    );
  }

  let payload: PicksFile;
  try {
    const text = fs.readFileSync(filePath, "utf-8");
    payload = JSON.parse(text);
  } catch {
    return NextResponse.json(
      { available: false, reason: `Failed to parse ${date}.json` },
      { status: 500, headers: { "cache-control": "no-store" } },
    );
  }

  const target = (payload.picks || []).find(p => String(p.game_pk) === String(game_pk));
  if (!target) {
    return NextResponse.json(
      {
        available: false,
        reason: `No pick entry for game_pk=${game_pk} on ${date}. Possibly a PASS pick (these are skipped unless --include-pass was used).`,
      },
      { headers: { "cache-control": "no-store" } },
    );
  }

  // T4.18: surface the model_version recorded at predict time (e.g. "V2.1")
  // alongside the per-pick reasoning, so the dashboard panel can show
  // exactly which model wrote this pick.  Falls back to "unknown" for
  // historical pick files written before T4.18 landed.
  const modelVersion = (payload as { model_version?: string }).model_version ?? "unknown";
  return NextResponse.json(
    { available: true, model_version: modelVersion, ...target },
    { headers: { "cache-control": "no-store" } },
  );
}
