#!/usr/bin/env python3
"""
tools/model_gate.py -- does this change move the model, and if so, which way?

WHY THIS EXISTS (T8.28).  From 2026-05-06 to 2026-08-10 this repo had NO
automatic check on model quality, while docs/PLAYBOOK.md section 4 told
every reader that merging a predictor PR "will run automatically" against
a shadow gate and fail under `delta_pl < -2.0u`.  That workflow had been
deleted three months earlier.  Anyone following the playbook merged a
predictor change believing a model check had passed.  Nothing ran.

`tests.yml` runs on every push, but it proves the money PLUMBING is
self-consistent -- Python, the parity fixtures and the dashboard's
TypeScript all agree on a number.  A change that quietly makes the
PREDICTIONS worse passes every bit of it green.  This closes that.

WHAT IT PROVES, AND WHAT IT DOES NOT
------------------------------------
It re-scores a fixed, committed holdout of real 2026 games with whatever
model code and artifacts are in the working tree, and emits a fingerprint
plus metrics.  Run it at two commits and compare:

  * FINGERPRINTS IDENTICAL -> the change provably did not move a single
    prediction.  This is the common and most valuable case: refactors,
    logging, ops and dashboard work should all land here, and any that
    does NOT is telling you something you did not expect.
  * FINGERPRINTS DIFFER    -> the change moves predictions.  The metric
    deltas say which way, on this holdout.

It does NOT prove a change is safe to ship.  The holdout is 2026 only
(see below), so it cannot speak to cross-year transfer, and a metric win
on ~1,000 games is weak evidence -- `2026-08-03_gate_sweep_artifact`
records a finding that passed a permutation null at p=0.000 AND
walk-forward 4-of-4 and was still an artifact.  The three-split
out-of-sample protocol CLAUDE.md calls non-negotiable is still yours to
run.  This is a tripwire, not a verdict.

WHY 2026 ONLY.  The three-split protocol wants repaired 2024 and 2025
files, and `_ptfix` is the repair (`_pit` is NOT -- that name has misled
two sessions; see the training-data-leakage memory).  The 2024/2025
`_ptfix` files are not in git and cannot be rebuilt in CI: they are
generated by `tools/backfill_pit_pitching_stats.py` from
`data/cache/pitcher_gamelog_v2/`, a 232MB gitignored cache.  Committing
them is 13MB and is SAFE from the Vercel bundle (`copy-data.mjs` uses an
allowlist that never copies `data/backtests/`), so this is an upgrade
path, not a wall.  Operator chose 2026-only on 2026-08-10 to avoid repo
growth.

WHY IT ONLY WARNS.  Operator's call, 2026-08-10, and it is the right one:
this branch takes ~30 automated pushes a day and a red gate during a live
slate could block a real fix under time pressure.  The report is loud;
the exit code is always 0.  Turning it into a blocker is a one-line
change in the workflow, deliberately not taken.

RE-SCORES FROM FEATURE COLUMNS, NEVER FROM THE VERDICT COLUMNS.
`pick_side` / `pick_strength` / `nrfi_prob` / `lambda_total` in the
backtest files are retired-Poisson artifacts that were never rebuilt --
measured AUC ~0.50, a coin flip.  Reading them as "what the model would
have done" is the single most repeated mistake in this repo's history.
This script builds features and calls the live model.

USAGE
    python tools/model_gate.py --fingerprint out.json
    python tools/model_gate.py --compare base.json candidate.json
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# The committed 2026 holdout. Both files are tracked, `_ptfix` (repaired),
# and carry real `actual_result` outcomes.
HOLDOUTS = [
    ROOT / "data/backtests/backtest_2026-04-01_to_2026-05-11_truepit_ptfix.csv",
    ROOT / "data/backtests/backtest_2026-05-12_to_2026-05-26_truepit_ptfix.csv",
]

# Rounded before hashing so that pure floating-point noise -- a different
# BLAS, a reordered sum -- does not masquerade as a model change. 9 places
# is far finer than any real model movement and far coarser than FP jitter.
FP_PLACES = 9

# Coverage floor. 524 of 735 holdout rows scored on 2026-08-10; the 211 skips
# are dominated by a missing `wx_wind_kmh` column in the backtest file. See
# the check in score_holdout() for why this is a loud warning and not a
# failure.
EXPECTED_ROWS = 524
MIN_ROWS = 450


def _f(row: dict, key: str) -> float | None:
    """Read a float from a CSV cell, treating blanks as missing."""
    v = (row.get(key) or "").strip()
    if v == "":
        return None
    try:
        return float(v)
    except ValueError:
        return None


def _feats(row: dict, names: list[str], derived: dict) -> list[float] | None:
    """Build a feature vector in the model's declared order.

    Returns None if any feature is missing, and the caller SKIPS that row.
    Skipping rather than imputing is deliberate: a zero-filled feature is a
    silent lie that would move the prediction and be attributed to the
    change under test.
    """
    out = []
    for n in names:
        v = derived[n] if n in derived else _f(row, n)
        if v is None:
            return None
        out.append(v)
    return out


def score_holdout() -> dict:
    """Score every usable holdout row with the working tree's model."""
    import mlb_first_inning_predictor as mp

    t1_names = mp._T1_EXPECTED_FEATURES
    b1_names = mp._B1_EXPECTED_FEATURES
    cal = mp._load_lr_calibrator()
    cal_apply = None
    if cal is not None:
        for meth in ("apply", "transform", "predict", "calibrate", "__call__"):
            if hasattr(cal, meth):
                cal_apply = getattr(cal, meth)
                break

    preds: dict[str, float] = {}
    ys: dict[str, int] = {}
    skipped = 0

    for path in HOLDOUTS:
        if not path.exists():
            raise SystemExit(f"holdout missing: {path}")
        for row in csv.DictReader(path.open(encoding="utf-8")):
            res = (row.get("actual_result") or "").strip().upper()
            if res not in ("NRFI", "YRFI"):
                skipped += 1
                continue

            h_era, a_era = _f(row, "home_era"), _f(row, "away_era")
            if h_era is None or a_era is None:
                skipped += 1
                continue
            derived = {"era_gap_t1": h_era - a_era, "era_gap_b1": a_era - h_era}

            t1 = _feats(row, t1_names, derived)
            b1 = _feats(row, b1_names, derived)
            if t1 is None or b1 is None:
                skipped += 1
                continue

            raw = mp.lr_predict_nrfi(t1, b1)
            if raw is None:
                skipped += 1
                continue
            p = raw
            if cal_apply is not None:
                try:
                    p = float(cal_apply(raw))
                except Exception:
                    p = raw

            # Stable key: date + teams. Sorted output makes the hash
            # independent of file or row ordering.
            key = f"{(row.get('date') or '').strip()}|{(row.get('away_team') or '').strip()}@{(row.get('home_team') or '').strip()}"
            if key in preds:            # doubleheader: disambiguate
                key += f"|{len(preds)}"
            preds[key] = round(float(p), FP_PLACES)
            ys[key] = 1 if res == "NRFI" else 0

    if not preds:
        raise SystemExit(
            "model_gate scored 0 rows -- the holdout, the feature names or the "
            "model artifacts changed shape. Investigate; do not ignore."
        )

    # A GUARD THAT QUIETLY STOPS GUARDING IS THE T8.28 FAILURE AGAIN.
    # `_feats` skips any row with a missing feature, so renaming one feature
    # would not crash -- it would silently shrink the holdout, and a gate
    # scoring 6 games would still cheerfully report "predictions unchanged".
    # 524 of 735 rows scored on 2026-08-10 (the 211 skips are overwhelmingly
    # absent `wx_wind_kmh`, a coverage hole in the backtest file, not a model
    # fault). Warn hard below 450 rather than fail, so a genuine data gap
    # cannot block a push -- but nobody can miss it either.
    if len(preds) < MIN_ROWS:
        msg = (f"model_gate coverage collapsed to {len(preds)} rows "
               f"(expected ~{EXPECTED_ROWS}, floor {MIN_ROWS}). A feature was "
               f"probably renamed or the holdout changed. THE GATE IS NOT "
               f"MEASURING WHAT YOU THINK IT IS.")
        print(f"::error::{msg}", file=sys.stderr)
        print(f"!! {msg}", file=sys.stderr)

    keys = sorted(preds)
    blob = "\n".join(f"{k}={preds[k]:.{FP_PLACES}f}" for k in keys)
    return {
        "fingerprint": hashlib.sha256(blob.encode()).hexdigest(),
        "n": len(keys),
        "skipped": skipped,
        "metrics": _metrics([preds[k] for k in keys], [ys[k] for k in keys]),
        "preds": {k: preds[k] for k in keys},
    }


def _metrics(ps: list[float], ys: list[int]) -> dict:
    """Brier and log loss (both LOWER IS BETTER), plus distribution shape.

    Brier is the headline because it is proper -- it cannot be gamed by
    shifting confidence without improving discrimination -- and because the
    repo's own retrain comparisons are argued on Brier.
    """
    n = len(ps)
    brier = sum((p - y) ** 2 for p, y in zip(ps, ys)) / n
    eps = 1e-12
    ll = -sum(
        y * math.log(max(p, eps)) + (1 - y) * math.log(max(1 - p, eps))
        for p, y in zip(ps, ys)
    ) / n
    return {
        "brier": round(brier, 6),
        "log_loss": round(ll, 6),
        "mean_pred": round(sum(ps) / n, 6),
        "base_rate": round(sum(ys) / n, 6),
        "min_pred": round(min(ps), 6),
        "max_pred": round(max(ps), 6),
    }


def compare(base: dict, cand: dict) -> None:
    """Print the report. Never raises, never exits non-zero -- warn-only."""
    bar = "=" * 68
    print(bar)
    print("MODEL GATE (T8.28) -- 2026 holdout, warn-only")
    print(bar)

    if base.get("fingerprint") == cand.get("fingerprint"):
        print(f"\n  PREDICTIONS UNCHANGED across {cand['n']} games.")
        print("  This change provably did not move the model.\n")
        print(f"  fingerprint {cand['fingerprint'][:16]}  brier "
              f"{cand['metrics']['brier']}")
        print(bar)
        return

    print("\n  *** PREDICTIONS MOVED ***\n")
    if base.get("n") != cand.get("n"):
        print(f"  !! Scored row count changed: {base.get('n')} -> {cand.get('n')}.")
        print("     Metric deltas below are NOT comparable across different")
        print("     row sets. Find out why the coverage changed first.\n")

    bp, cp = base.get("preds", {}), cand.get("preds", {})
    shared = sorted(set(bp) & set(cp))
    moved = [(k, cp[k] - bp[k]) for k in shared if cp[k] != bp[k]]
    if shared:
        print(f"  games moved: {len(moved)} of {len(shared)} shared")
    if moved:
        diffs = sorted((abs(d) for _, d in moved), reverse=True)
        print(f"  largest move: {diffs[0]:.6f}   median move: "
              f"{diffs[len(diffs)//2]:.6f}")
        print("\n  most-moved games:")
        for k, d in sorted(moved, key=lambda kv: -abs(kv[1]))[:5]:
            print(f"    {k:34s} {bp[k]:.4f} -> {cp[k]:.4f}  ({d:+.4f})")

    print("\n  metric            base        candidate   delta")
    for m in ("brier", "log_loss", "mean_pred"):
        b, c = base["metrics"].get(m), cand["metrics"].get(m)
        if b is None or c is None:
            continue
        d = c - b
        note = ""
        if m in ("brier", "log_loss"):
            note = "  BETTER" if d < 0 else ("  WORSE" if d > 0 else "  same")
        print(f"  {m:16s}  {b:<11.6f} {c:<11.6f} {d:+.6f}{note}")

    print("\n  Brier and log loss are LOWER-IS-BETTER.")
    print("  A win here is NOT proof the change is good: this is ~1,000 games")
    print("  of 2026 only. Run the three-split out-of-sample protocol before")
    print("  shipping a model change, and get the operator's sign-off.")
    print(bar)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--fingerprint", metavar="OUT.json",
                    help="score the holdout with the current tree")
    ap.add_argument("--compare", nargs=2, metavar=("BASE.json", "CAND.json"),
                    help="report the difference between two fingerprints")
    a = ap.parse_args()

    if a.fingerprint:
        res = score_holdout()
        Path(a.fingerprint).write_text(json.dumps(res, indent=1), encoding="utf-8")
        print(f"scored {res['n']} games (skipped {res['skipped']})  "
              f"brier {res['metrics']['brier']}  "
              f"fingerprint {res['fingerprint'][:16]}")
        return 0

    if a.compare:
        b = json.loads(Path(a.compare[0]).read_text(encoding="utf-8"))
        c = json.loads(Path(a.compare[1]).read_text(encoding="utf-8"))
        compare(b, c)
        return 0            # warn-only, always

    ap.print_help()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
