#!/usr/bin/env python3
"""tools/v21_shadow_predict.py

Run the archived V2.1 LR weights + V2.1 calibrator on TODAY's picks
data (already generated by V2.2) and stamp what V2.1 *would* have
predicted into the same row.

This does NOT touch any V2.2 decision -- pick_side, pick_strength,
pick_label, bet_placed, units_risked all stay as the live model
produced them.  We only fill the three new shadow columns:

    v21_shadow_nrfi_prob       calibrated P(NRFI) under V2.1
    v21_shadow_pick_side       NRFI | YRFI | PASS (V2.1's verdict)
    v21_shadow_pick_strength   STRONG | NO EDGE

Why this exists: the 2026-05-11 V2.2 deploy bumped LR weights to
match the 5/03-corrected truepit backtests.  Forward-sim on 5/09-5/10
showed +3.17u improvement, but with only ~5 days of comparison we
don't yet know if V2.2 holds up over a real ~30-bet sample.  This
shadow gives us actual head-to-head data without risking real money
on V2.1.

Pair this script with tools/v21_vs_v22_compare.py, which reads the
shadow columns and reports daily / trailing W-L + P&L for both
versions.

Usage:
  python tools/v21_shadow_predict.py             # ET today
  python tools/v21_shadow_predict.py --date 2026-05-12
  python tools/v21_shadow_predict.py --dry-run   # report; no write

Idempotent: re-running on an already-shadowed row updates the shadow
columns to the current V2.1 prediction (since features may have
refreshed since the last predict cron).
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import numpy as np

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import tracker  # noqa: E402

ET = ZoneInfo("America/New_York")

# Same thresholds as production -- mirror predictor's classification logic.
STRONG_NRFI_P    = 0.56
PASS_LO_P        = 0.44
LAMBDA_YRFI_FLOOR = 0.78

# Same default constants as recalibrate_v2 / two_stage_model
LEAGUE_AVG_ERA = 4.20
LEAGUE_AVG_OBP = 0.318
LEAGUE_AVG_SLG = 0.414
LEAGUE_AVG_ISO = 0.169
FI_PARK_DEFAULT = 0.50
WX_TEMP_DEFAULT, WX_WIND_DEFAULT, WX_HUMIDITY_DEFAULT = 20.0, 10.0, 60.0
LEAGUE_NRFI_RATE = 0.50
LEAGUE_AVG_XERA = 4.20
NEUTRAL_PCT_RANK = 50

# Feature order MUST match what the V2.1 LR was trained on.  This is
# locked because we're loading the archived V2.1 weights file -- if it
# was trained on a different order, the products are nonsense.  See
# recalibrate_v2.py T1_FEATURES / B1_FEATURES.
T1_FEATURES = [
    "fi_park_nrfi_rate", "home_fip", "away_obp",
    "wx_temp_c", "wx_wind_kmh", "wx_humidity", "wx_is_dome",
    "home_p_last5_pitcher_nrfi",
    "away_top3c_obp",
    "home_plate_ump_nrfi_rate",
    "home_xera",
    "home_whiff_pct_rank",
    "era_gap_t1",
    "home_p_last10_pitcher_nrfi",
    "away_top3c_slg",
    "away_top3c_iso",
    "home_pvt_nrfi_rate",
    "home_avg_ip_per_start",
]
B1_FEATURES = [
    "fi_park_nrfi_rate", "away_fip", "home_obp",
    "wx_temp_c", "wx_wind_kmh", "wx_humidity", "wx_is_dome",
    "away_p_last5_pitcher_nrfi",
    "home_top3c_obp",
    "home_plate_ump_nrfi_rate",
    "away_xera",
    "away_whiff_pct_rank",
    "era_gap_b1",
    "away_p_last10_pitcher_nrfi",
    "home_top3c_slg",
    "home_top3c_iso",
    "away_pvt_nrfi_rate",
    "away_avg_ip_per_start",
]


def _coerce(s, d):
    try:
        return float(s)
    except (TypeError, ValueError):
        return d


def _build_features(r: dict, fipark: dict) -> tuple[list[float], list[float]] | None:
    """Reconstruct (T1, B1) feature vectors from a CSV row.  Returns
    None if the row is missing a required field."""
    home = r.get("home_team") or ""
    fi_park = fipark.get(home, FI_PARK_DEFAULT)
    wx_t = _coerce(r.get("wx_temp_c"), WX_TEMP_DEFAULT)
    wx_w = _coerce(r.get("wx_wind_kmh"), WX_WIND_DEFAULT)
    wx_h = _coerce(r.get("wx_humidity"), WX_HUMIDITY_DEFAULT)
    wx_d = _coerce(r.get("wx_is_dome"), 0.0)
    ump  = _coerce(r.get("home_plate_ump_nrfi_rate"), LEAGUE_NRFI_RATE)
    h_era = _coerce(r.get("home_era"), LEAGUE_AVG_ERA)
    a_era = _coerce(r.get("away_era"), LEAGUE_AVG_ERA)
    t1 = [
        fi_park,
        _coerce(r.get("home_fip"), LEAGUE_AVG_ERA),
        _coerce(r.get("away_obp"), LEAGUE_AVG_OBP),
        wx_t, wx_w, wx_h, wx_d,
        _coerce(r.get("home_p_last5_pitcher_nrfi"), LEAGUE_NRFI_RATE),
        _coerce(r.get("away_top3c_obp"), LEAGUE_AVG_OBP),
        ump,
        _coerce(r.get("home_xera"), LEAGUE_AVG_XERA),
        _coerce(r.get("home_whiff_pct_rank"), NEUTRAL_PCT_RANK),
        h_era - a_era,
        _coerce(r.get("home_p_last10_pitcher_nrfi"), LEAGUE_NRFI_RATE),
        _coerce(r.get("away_top3c_slg"), LEAGUE_AVG_SLG),
        _coerce(r.get("away_top3c_iso"), LEAGUE_AVG_ISO),
        _coerce(r.get("home_pvt_nrfi_rate"), LEAGUE_NRFI_RATE),
        _coerce(r.get("home_avg_ip_per_start"), 5.0),
    ]
    b1 = [
        fi_park,
        _coerce(r.get("away_fip"), LEAGUE_AVG_ERA),
        _coerce(r.get("home_obp"), LEAGUE_AVG_OBP),
        wx_t, wx_w, wx_h, wx_d,
        _coerce(r.get("away_p_last5_pitcher_nrfi"), LEAGUE_NRFI_RATE),
        _coerce(r.get("home_top3c_obp"), LEAGUE_AVG_OBP),
        ump,
        _coerce(r.get("away_xera"), LEAGUE_AVG_XERA),
        _coerce(r.get("away_whiff_pct_rank"), NEUTRAL_PCT_RANK),
        a_era - h_era,
        _coerce(r.get("away_p_last10_pitcher_nrfi"), LEAGUE_NRFI_RATE),
        _coerce(r.get("home_top3c_slg"), LEAGUE_AVG_SLG),
        _coerce(r.get("home_top3c_iso"), LEAGUE_AVG_ISO),
        _coerce(r.get("away_pvt_nrfi_rate"), LEAGUE_NRFI_RATE),
        _coerce(r.get("away_avg_ip_per_start"), 5.0),
    ]
    return t1, b1


def _load_lr(path: Path) -> dict:
    with open(path, encoding="utf-8") as f:
        d = json.load(f)
    return {
        "feature_names": d["feature_names"],
        "weights":       np.asarray(d["weights"], dtype=float),
        "bias":          float(d["bias"]),
        "mean":          np.asarray(d["mean"], dtype=float),
        "std":           np.asarray(d["std"], dtype=float),
    }


def _predict(m: dict, X: np.ndarray) -> np.ndarray:
    Xn = (X - m["mean"]) / m["std"]
    z = Xn @ m["weights"] + m["bias"]
    return 1.0 / (1.0 + np.exp(-z))


def _classify(p_cal: float, lam_total: float) -> tuple[str, str]:
    """Same classification logic the predictor uses for V2.2.  Mirrors
    mlb_first_inning_predictor.py's STRONG/PASS rules.

    Returns (pick_side, pick_strength).
    """
    if p_cal >= STRONG_NRFI_P:
        return "NRFI", "STRONG"
    if p_cal < PASS_LO_P:
        if lam_total >= LAMBDA_YRFI_FLOOR:
            return "YRFI", "STRONG"
        return "PASS", "NO EDGE"
    return "PASS", "NO EDGE"


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--date", help="ET slate date YYYY-MM-DD (default: today).")
    p.add_argument("--season", type=int, default=None)
    p.add_argument("--dry-run", action="store_true")
    args = p.parse_args()

    target = args.date or datetime.now(ET).strftime("%Y-%m-%d")
    season = args.season or int(target[:4])
    csv_path = tracker._csv_path(season)
    archive = ROOT / "data" / "archive" / "v2.1"
    t1_path = archive / "lr_t1.json"
    b1_path = archive / "lr_b1.json"
    cal_path = archive / "calibration_v2.json"
    for need in (t1_path, b1_path, cal_path):
        if not need.exists():
            print(f"ERROR: V2.1 archive missing -- expected {need}", file=sys.stderr)
            return 2

    t1m = _load_lr(t1_path)
    b1m = _load_lr(b1_path)
    # Sanity: archived V2.1 should have same feature order we hardcoded.
    if t1m["feature_names"] != T1_FEATURES:
        print(f"ERROR: V2.1 T1 feature order mismatch.", file=sys.stderr)
        print(f"  archive: {t1m['feature_names']}", file=sys.stderr)
        print(f"  expected: {T1_FEATURES}", file=sys.stderr)
        return 2
    if b1m["feature_names"] != B1_FEATURES:
        print(f"ERROR: V2.1 B1 feature order mismatch.", file=sys.stderr)
        return 2

    from calibration import ProbCalibrator
    cal = ProbCalibrator.load(cal_path)

    # Load FI park map -- T1 row had `fi_park_nrfi_rate` available from
    # the LIVE predictor's input.  Re-derive identically.
    fipark_path = ROOT / "data" / "fi_park_factors.json"
    fipark = {}
    if fipark_path.exists():
        with open(fipark_path, encoding="utf-8") as f:
            fipark = json.load(f)

    if not csv_path.exists():
        print(f"ERROR: ledger not found at {csv_path}", file=sys.stderr)
        return 2
    rows = tracker._read_rows(csv_path)
    target_rows = [(i, r) for i, r in enumerate(rows) if r.get("date") == target]
    print(f"v21_shadow_predict  date={target}  slate_rows={len(target_rows)}  dry_run={args.dry_run}")

    n_shadowed = 0
    n_skipped = 0
    flips_strong = 0   # V2.2 STRONG, V2.1 PASS  (V2.1 would have skipped)
    flips_strong_other = 0  # V2.2 PASS, V2.1 STRONG (V2.1 would have bet)

    for idx, r in target_rows:
        # Skip rows the live predictor hasn't actually predicted yet
        # (no pick_strength means we're pre-prediction).
        if not (r.get("pick_strength") or "").strip():
            n_skipped += 1
            continue

        feats = _build_features(r, fipark)
        if feats is None:
            n_skipped += 1
            continue
        t1v, b1v = feats

        X_t1 = np.asarray([t1v], dtype=float)
        X_b1 = np.asarray([b1v], dtype=float)
        p_t1 = _predict(t1m, X_t1)[0]
        p_b1 = _predict(b1m, X_b1)[0]
        p_nrfi_raw = (1.0 - p_t1) * (1.0 - p_b1)
        p_nrfi_cal = float(cal.predict(float(p_nrfi_raw)))

        lam_total = _coerce(r.get("combined_lambda") or r.get("lambda_lr_total"), 1.0)
        v21_side, v21_strength = _classify(p_nrfi_cal, lam_total)

        # Track flips for stdout summary
        v22_side = (r.get("pick_side") or "").upper()
        v22_strength = (r.get("pick_strength") or "").upper()
        # Treat CLUSTER-DEMOTED rows as their original verdict for flip
        # accounting, since they were originally STRONG (NRFI/YRFI) before
        # the demotion rewrote them to PASS.
        if v22_strength in ("PASS", "NO EDGE") and "CLUSTER DEMOTED" in (r.get("pick_label") or ""):
            # extract original verdict from label if possible
            import re
            mat = re.search(r"STRONG (NRFI|YRFI)", r.get("pick_label", ""))
            if mat:
                v22_side, v22_strength = mat.group(1), "STRONG"

        if v22_strength == "STRONG" and v21_strength != "STRONG":
            flips_strong += 1
        if v22_strength != "STRONG" and v21_strength == "STRONG":
            flips_strong_other += 1

        rows[idx]["v21_shadow_nrfi_prob"] = f"{p_nrfi_cal:.4f}"
        rows[idx]["v21_shadow_pick_side"] = v21_side
        rows[idx]["v21_shadow_pick_strength"] = v21_strength
        n_shadowed += 1

    print(f"  V2.2 STRONG -> V2.1 would PASS:    {flips_strong}")
    print(f"  V2.2 PASS   -> V2.1 would STRONG:  {flips_strong_other}")
    print(f"  shadowed={n_shadowed}, skipped={n_skipped}")

    if args.dry_run:
        print("\n[dry-run] not writing CSV.")
        return 0
    if n_shadowed == 0:
        return 0
    tracker._write_rows(csv_path, rows)
    print(f"  Wrote shadow columns for {n_shadowed} row(s) on {target}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
